version: "3"
services:
    database:
        container_name: elok-quiz-db
        image: mysql:8.0.21
        environment:
            MYSQL_ROOT_PASSWORD: pwd!
            MYSQL_DATABASE: quiz
            MYSQL_USER: quiz-app
            MYSQL_PASSWORD: 9876
        ports:
            - 3316:3306
        restart: always
        networks:
            - quizBackendNetwork
    elok-quiz:
        container_name: elok-quiz
        depends_on:
            - database
        image: elok-quiz:0.0.2
        build: ./
        ports:
            - 8888:8888
        restart: always
        networks:
            - quizBackendNetwork
            - quizFrontendNetwork
        volumes:
            - elok-pictures:/images/questions
    elok-quiz-frontend:
        container_name: elok-quiz-frontend
        image: elok-quiz-frontend:0.0.1
        build: ./quiz-frontend
        ports:
            - 80:80
        networks:
            - quizFrontendNetwork

networks:
    quizBackendNetwork:
    quizFrontendNetwork:
    
volumes:
   elok-pictures:
      driver: local
      driver_opts:
        type: none
        device: $HOME/volumes/quiz/elok-pictures
        o: bind